package:
    name: scansnv
    version: "0.9"

requirements:
    run:
        - blas 1.0 mkl
        - bwidget 1.9.11 1
        - conda-env 2.6.0 1
        - datrie 0.7.1 py36h7b6447c_1
        - gsl 2.2.1 h0c605f7_3
        - intel-openmp 2019.1 144
        - libedit 3.1.20170329 h6b74fdf_2
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 8.2.0 hdf63c60_1
        - libgfortran 3.0.0 1
        - libgfortran-ng 7.2.0 hdf63c60_3
        - liblief 0.9.0 h7725739_1
        - libstdcxx-ng 8.2.0 hdf63c60_1
        - mkl 2019.1 144
        - ncurses 6.1 hf484d3e_0
        - py-lief 0.9.0 py36h7725739_1
        - readline 7.0 h7b6447c_5
        - requests 2.13.0 py36_0
        - sqlite 3.25.3 h7b6447c_0
        - tk 8.6.8 hbc83047_0
        - tktable 2.10 h14c3975_0
        - wheel 0.32.3 py36_0
        - xz 5.2.4 h14c3975_4
        - yaml 0.1.7 had09818_2
        - zlib 1.2.11 ha838bed_2
        - bedtools 2.27.1 he941832_2
        - filechunkio 1.6 py36_0
        - ftputil 3.2 py36_0
        - gatk 3.8 py36_0
        - libdeflate 1.0 h470a237_0
        - pyasn1-modules 0.0.5 py36_0
        - pygraphviz 1.3.1 py36_0
        - rsa 3.1.4 py36_0
        - samtools 1.9 h8ee4bcc_1
        - shapeit 2.r837 h09b0a5c_1
        - snakemake 5.3.1 0
        - snakemake-minimal 5.3.1 py_0
        - urllib3 1.12 py36_0
        - aioeasywebdav 2.2.0 py36_0
        - aiohttp 3.4.4 py36h470a237_0
        - anaconda-client 1.7.1 py_0
        - appdirs 1.4.3 py_1
        - asn1crypto 0.24.0 py36_1003
        - async-timeout 3.0.1 py_1000
        - attrs 18.2.0 py_0
        - bcrypt 3.1.4 py36h470a237_0
        - beautifulsoup4 4.6.3 py36_1000
        - boost 1.66.0 py36_1
        - boost-cpp 1.66.0 1
        - boto3 1.7.84 py_0
        - botocore 1.10.84 py_0
        - bzip2 1.0.6 h470a237_2
        - ca-certificates 2018.11.29 ha4d7672_0
        - cachetools 2.1.0 py_0
        - cairo 1.14.12 h276e583_5
        - certifi 2018.11.29 py36_1000
        - cffi 1.11.5 py36h5e8e0c9_1
        - chardet 3.0.4 py36_1003
        - clyent 1.2.2 py_1
        - conda 4.5.12 py36_1000
        - conda-build 3.17.5 py36_0
        - configargparse 0.13.0 py_1
        - cryptography 2.3.1 py36hdffb7b8_0
        - cryptography-vectors 2.3.1 py36_1000
        - curl 7.63.0 h74213dd_0
        - decorator 4.3.0 py_0
        - docutils 0.14 py36_1001
        - dropbox 7.3.1 py36_0
        - expat 2.2.5 hfc679d8_2
        - filelock 3.0.10 py_0
        - fontconfig 2.13.1 h65d0f4c_0
        - freetype 2.9.1 h6debe1e_4
        - gettext 0.19.8.1 h5e8e0c9_1
        - gitdb2 2.0.5 py_0
        - gitpython 2.1.11 py_0
        - glib 2.56.2 h464dc38_1
        - glob2 0.6 py_0
        - google-auth 1.2.1 py_0
        - google-auth-httplib2 0.0.3 py_2
        - google-cloud-core 0.24.1 py36_0
        - google-cloud-storage 1.1.1 py36_0
        - google-resumable-media 0.0.2 py36_0
        - googleapis-common-protos 1.5.5 py_0
        - graphite2 1.3.12 hfc679d8_1
        - graphviz 2.38.0 h08bfae6_9
        - harfbuzz 1.9.0 h04dbb29_1
        - httplib2 0.12.0 py36_1000
        - icu 58.2 hfc679d8_0
        - idna 2.8 py36_1000
        - idna_ssl 1.0.0 0
        - ipython_genutils 0.2.0 py_1
        - jinja2 2.10 py_1
        - jmespath 0.9.3 py_1
        - jpeg 9c h470a237_1
        - jsonschema 3.0.0a3 py36_1000
        - jupyter_core 4.4.0 py_0
        - krb5 1.16.2 hbb41f41_0
        - libarchive 3.3.3 h823be47_0
        - libcurl 7.63.0 hbdb9355_0
        - libiconv 1.15 h470a237_3
        - libpng 1.6.36 ha92aebf_0
        - libprotobuf 3.6.1 hd28b015_0
        - libssh2 1.8.0 h5b517e9_3
        - libtiff 4.0.10 he6b73bb_1
        - libtool 2.4.6 h470a237_2
        - libuuid 2.32.1 h470a237_2
        - libxcb 1.13 h470a237_2
        - libxml2 2.9.8 h422b904_5
        - make 4.2.1 h470a237_1002
        - markupsafe 1.1.0 py36h470a237_0
        - mkl_fft 1.0.10 py36_0
        - mkl_random 1.0.2 py36_0
        - multidict 4.5.1 py36h470a237_0
        - nbformat 4.4.0 py_1
        - networkx 2.2 py_1
        - openblas 0.3.4 ha44fe06_0
        - openjdk 8.0.192 h470a237_2
        - openssl 1.0.2p h470a237_1
        - pandas 0.23.4 py36hf8a1672_0
        - pango 1.40.14 he752989_2
        - paramiko 2.4.2 py36_1000
        - patchelf 0.9 hfc679d8_2
        - pcre 8.41 hfc679d8_3
        - pip 18.1 py36_1000
        - pixman 0.34.0 h470a237_3
        - pkginfo 1.4.2 py_1
        - prettytable 0.7.2 py_2
        - protobuf 3.6.1 py36hfc679d8_1
        - psutil 5.4.8 py36h470a237_0
        - pthread-stubs 0.4 h470a237_1
        - pyasn1 0.4.4 py_1
        - pycosat 0.6.3 py36h470a237_1
        - pycparser 2.19 py_0
        - pynacl 1.3.0 py36h470a237_0
        - pyopenssl 18.0.0 py36_1000
        - pyrsistent 0.14.7 py36h470a237_0
        - pysftp 0.2.9 py36_0
        - pysocks 1.6.8 py36_1002
        - python 3.6.6 h5001a0f_3
        - python-dateutil 2.7.5 py_0
        - python-irodsclient 0.7.0 py_0
        - python-libarchive-c 2.8 py36_1004
        - pytz 2018.7 py_0
        - pyyaml 3.13 py36h470a237_1
        - r-assertthat 0.2.0 r351h6115d3f_1001
        - r-base 3.5.1 h391c2eb_4
        - r-bh 1.66.0_1 r351_2001
        - r-bindr 0.1.1 r351h6115d3f_1001
        - r-bindrcpp 0.2.2 r351h9d2a408_1
        - r-bit 1.1_12 r351h470a237_2
        - r-bit64 0.9_7 r351hc070d10_0
        - r-blob 1.1.1 r351_1001
        - r-cli 1.0.1 r351h6115d3f_1000
        - r-crayon 1.3.4 r351h6115d3f_1001
        - r-dbi 1.0.0 r351h6115d3f_1001
        - r-dbplyr 1.2.2 r351h6115d3f_1001
        - r-digest 0.6.18 r351hc070d10_0
        - r-dplyr 0.7.8 r351h9d2a408_0
        - r-fansi 0.3.0 r351hc070d10_0
        - r-glue 1.3.0 r351h470a237_2
        - r-magrittr 1.5 r351h6115d3f_1001
        - r-memoise 1.1.0 r351h6115d3f_1001
        - r-pillar 1.3.0 r351h6115d3f_1000
        - r-pkgconfig 2.0.2 r351h6115d3f_1001
        - r-plogr 0.2.0 r351h6115d3f_1001
        - r-prettyunits 1.0.2 r351h6115d3f_1001
        - r-purrr 0.2.5 r351hc070d10_2
        - r-r6 2.2.2 r351h6115d3f_1001
        - r-rcpp 1.0.0 r351h9d2a408_0
        - r-rlang 0.3.0.1 r351h470a237_0
        - r-rsqlite 2.1.1 r351h9d2a408_0
        - r-tibble 1.4.2 r351hc070d10_2
        - r-tidyselect 0.2.5 r351h9d2a408_0
        - r-utf8 1.1.4 r351hc070d10_0
        - ratelimiter 1.2.0 py36_1000
        - rpy2 2.9.4 py36r351h941a26a_1
        - ruamel_yaml 0.15.71 py36h470a237_0
        - s3transfer 0.1.13 py36_1001
        - setuptools 40.6.3 py36_0
        - six 1.12.0 py36_1000
        - smmap2 2.0.5 py_0
        - tqdm 4.28.1 py_0
        - traitlets 4.3.2 py36_1000
        - tzlocal 1.5.1 py_0
        - wrapt 1.10.11 py36h470a237_1
        - xmlrunner 1.7.7 py_0
        - xorg-kbproto 1.0.7 h470a237_2
        - xorg-libice 1.0.9 h470a237_4
        - xorg-libsm 1.2.3 h8c8a85c_0
        - xorg-libx11 1.6.6 h470a237_0
        - xorg-libxau 1.0.8 h470a237_6
        - xorg-libxdmcp 1.1.2 h470a237_7
        - xorg-libxext 1.3.3 h470a237_4
        - xorg-libxpm 3.5.12 h470a237_2
        - xorg-libxrender 0.9.10 h470a237_2
        - xorg-libxt 1.1.5 h470a237_2
        - xorg-renderproto 0.11.1 h470a237_2
        - xorg-xextproto 7.3.0 h470a237_2
        - xorg-xproto 7.0.31 h470a237_7
        - yarl 1.3.0 py36h470a237_0
        - _r-mutex 1.0.0 anacondar_1
        - numpy 1.15.4 py36h7e9f1db_0
        - numpy-base 1.15.4 py36hde5b4d6_0
        - r-fastghquad 1.0 r351h29659fb_0
        - r-scansnv
        - pip

source:
    git_url: https://github.com/parklab/scan-snv.git

about:
    home: https://github.com/parklab/scan-snv
    summary: SNV genotyper for MDA-amplified single cells
