package:
  name: r-scan2
  version: '1.0'

source:
  git_url: https://github.com/parklab/r-scan2.git

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 2
  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - toolchain        # [win]
    - filesystem        # [win]
    - make
    - sed               # [win]
    - coreutils         # [win]
    - zip               # [win]
  host:
    - python=3.8
    - r-base=4.1
    - openblas
    - r-plyr
    - r-pbapply
    - r-fastghquad
    - r-yaml
    - r-pracma
    - r-viridis
    - bioconductor-bsgenome.hsapiens.1000genomes.hs37d5
    - bioconductor-bsgenome.hsapiens.ncbi.grch38
    - r-lme4
    - r-lmerTest
    - r-argparse
    - r-data.table
    - r-reticulate
    - r-devtools
  run:
    - python=3.8
    - r-base=4.1
    - openblas
    - r-plyr
    - r-pbapply
    - r-fastghquad
    - r-yaml
    - r-pracma
    - r-viridis
    - bioconductor-bsgenome.hsapiens.1000genomes.hs37d5
    - bioconductor-bsgenome.hsapiens.ncbi.grch38
    - r-lme4
    - r-lmerTest
    - r-argparse
    - r-data.table
    - r-reticulate
    - r-devtools

test:
  commands:
    - $R -e "library('scan2')"           # [not win]
    - "\"%R%\" -e \"library('scan2')\""  # [win]

about:
  home: https://github.com/parklab/r-scan2
  summary: R objects for interactive single cell SNV and indel genotyping
