package:
    name: scan2
    version: "1.2.14"
    githash: {{ GIT_FULL_HASH }}

build:
    number: 1

requirements:
    run:
      - python
      - r-base
      - snakemake
      - java-jdk=8
      - shapeit
      - eagle-phase
      - gatk=3.8
      - gatk4
      - samtools
      - pysam
      - bedtools
      - htslib
      - bcftools>=1.19   # 1.19 is necessary for bcftools view -AA to remove <NON_REF>
      - r-scan2>=1.2.13
      - shyaml
      - r-argparse

source:
    git_url: https://github.com/parklab/SCAN2.git

about:
    home: https://github.com/parklab/SCAN2
    summary: Somatic SNV and indel genotyper for PTA-amplified single cells
